project:
  type: website
  output-dir: docs
  
website:
  title: "Christopher B. Boyer"
  navbar:
    right:
      - blog.qmd
      - research.qmd
      - teaching.qmd
      - software.qmd
      - icon: github
        href: https://github.com/
      - text: "{{< iconify academicons cv size=lg >}}"
        href: files/cv.pdf
format:
  html:
    theme: cosmo
    css: styles.css



