project:
  type: website
  output-dir: docs
  
website:
  title: "Christopher B. Boyer"
  site-url: "https://boyercb.github.io"
  description: "Personal website of Christopher B. Boyer, Assistant Professor at Cleveland Clinic specializing in causal inference and biostatistics."
  open-graph: true
  twitter-card: true
  google-analytics: "G-1D051HLKQD"
  navbar:
    right:
      - blog.qmd
      - research.qmd
      - talks.qmd
      - teaching.qmd
      - software.qmd
      - icon: github
        href: https://github.com/
      - text: "{{< iconify academicons cv size=lg >}}"
        href: files/cv.pdf
format:
  html:
    theme: cosmo
    css: styles.css



