---
title: "Research"
format:
  html: 
    toc: false
---

### Pre-prints
- **Boyer, C.**, Li, K.Q., Shi, X., & Tchetgen Tchetgen, T. J. (2025). "Identification and estimation of vaccine effectiveness in the test-negative design under equi-confounding". *arXiv*. [https://doi.org/10.48550/arXiv.2504.20360](https://doi.org/10.48550/arXiv.2504.20360)

- Gago, J., **Boyer, C.**, & Lipsitch, M. How should we study the indirect effects of antimicrobial treatment strategies? A causal perspective. *medRxiv*. [https://doi.org/10.1101/2025.03.28.25324855](https://doi.org/10.1101/2025.03.28.25324855)

- **Boyer, C.**, Field, E., Lehrer, R., Morrison, A., & Piras, C. (2025). "Guy Talk: Catalyzing Peer Effects on IPV through Virtual Support Groups for Men". [https://sites.duke.edu/ericafield/files/2025/03/wp_2025_03_Guy_Talk_Peru.pdf](https://sites.duke.edu/ericafield/files/2025/03/wp_2025_03_Guy_Talk_Peru.pdf)

- **Boyer, C.**, Dahabreh, I. J., & Steingrimsson, J. A. (2024). "Estimating and evaluating counterfactual prediction models". *arXiv*. [https://doi.org/10.48550/arXiv.2308.13026](https://doi.org/10.48550/arXiv.2308.13026)

- Zhang, Z., **Boyer, C.**, Lipsitch, M. (2024). "Use of the test-negative design to estimate the protective effect of a scalar immune measure: A simulation analysis". *medRxiv*. [https://doi.org/10.1101/2024.11.22.24317757](https://doi.org/10.1101/2024.11.22.24317757)

- Joshi, K., Kahn, R., **Boyer, C.**, & Lipsitch, M. (2023). "Some principles for using epidemiologic study results to parameterize transmission models". *medRxiv*.  [https://doi.org/10.1101/2023.10.03.23296455](https://doi.org/10.1101/2023.10.03.23296455)


### Peer-reviewed publications
1. Jia, K. M., **Boyer, C.**, Wallinga, J., & Lipsitch, M. (2025). Causal Estimands for Analyses of Averted and Avertible Outcomes due to Infectious Disease Interventions. *Epidemiology*, 36(3), 363-373. [https://doi.org/10.1097/EDE.0000000000001839](https://doi.org/10.1097/EDE.0000000000001839) </br> {{< iconify fa pencil >}} [pre-print](https://www.medrxiv.org/content/10.1101/2022.01.07.21268585v2) / {{< iconify fa6-brands github >}} [repository](https://github.com/boyercb/covid-gathering-size) / {{< iconify fa-regular file-pdf >}} [pdf](files/Boyer%20et%20al.%20-%202022%20-%20Infectious%20disease%20dynamics%20and%20restrictions%20on%20so.pdf)

2. **Boyer, C.** & Lipsitch, M. (2024). Emulating target trials of postexposure vaccines using observational data. *American Journal of Epidemiology*. [https://doi.org/10.1093/aje/kwae350](https://doi.org/10.1093/aje/kwae350) </br> {{< iconify fa pencil >}} [pre-print](https://www.medrxiv.org/content/10.1101/2022.01.07.21268585v2) / {{< iconify fa6-brands github >}} [repository](https://github.com/boyercb/covid-gathering-size) / {{< iconify fa-regular file-pdf >}} [pdf](files/Boyer%20et%20al.%20-%202022%20-%20Infectious%20disease%20dynamics%20and%20restrictions%20on%20so.pdf)

3. **Boyer, C.**, Paluck, E. L., Annan, J., Nevatia, T., Cooper, J., Namubiru, J, Heise, L., & Lehrer, R. (2022) Religious leaders can motivate men to cede power and reduce intimate partner violence: experimental evidence from Uganda. *PNAS*. 119(31), e2200262119. [https://doi.org/10.1073/pnas.2200262119](https://doi.org/10.1073/pnas.2200262119) </br> {{< iconify carbon plan >}} [pre-analysis plan](https://www.socialscienceregistry.org/trials/3994/history/43131) / {{< iconify fa6-brands github >}} [repository](https://doi.org/10.7910/DVN/9TEAIV) / {{< iconify fa-regular file-pdf >}} [pdf](files/Boyer%20et%20al.%20-%202022%20-%20Religious%20leaders%20can%20motivate%20men%20to%20cede%20power%20a.pdf)

4. **Boyer, C.**, Rumpler, E., Kissler, S. M., & Lipsitch, M. (2022). Infectious disease dynamics and restrictions on social gathering size. *Epidemics*, 40, 100620. [https://doi.org/10.1016/j.epidem.2022.100620](https://doi.org/10.1016/j.epidem.2022.100620) </br> {{< iconify fa pencil >}} [pre-print](https://www.medrxiv.org/content/10.1101/2022.01.07.21268585v2) / {{< iconify fa6-brands github >}} [repository](https://github.com/boyercb/covid-gathering-size) / {{< iconify fa-regular file-pdf >}} [pdf](files/Boyer%20et%20al.%20-%202022%20-%20Infectious%20disease%20dynamics%20and%20restrictions%20on%20so.pdf)

5. Chatterji, S., **Boyer, C.**, Sharma, V., Abramsky, T., Levtov, R., Doyle, K., Harvey, S., & Heise, L. (2023). "Optimizing the Construction of Outcome Measures for Impact Evaluations of Intimate Partner Violence Prevention Interventions." *Journal of Interpersonal Violence*, 0(0). [https://doi.org/10.1177/08862605231162887](https://doi.org/10.1177/08862605231162887) </br> {{< iconify fa pencil >}} [pre-print](https://www.medrxiv.org/content/10.1101/2023.02.07.23285510.abstract) / {{< iconify fa-regular file-pdf >}} [pdf](files/Chatterji%20et%20al.%20-%202023%20-%20Optimizing%20the%20Construction%20of%20Outcome%20Measures%20fo.pdf)

6. Rosen, J. B., Arciuolo, R. J., Pathela, P., **Boyer, C.**, Baumgartner, J., Latash, J., Malec, L., Lee, E. H., Reddy, V., King, R., Edward Real, J., Lipsitch, M., & Zucker, J. R. (2024). JYNNEOS™ effectiveness as post-exposure prophylaxis against mpox: Challenges using real-world outbreak data. *Vaccine*. [https://doi.org/10.1016/j.vaccine.2023.12.066](https://doi.org/10.1016/j.vaccine.2023.12.066) </br> {{< iconify fa-regular file-pdf >}} [pdf](files/Rosen%20et%20al.%20-%202024%20-%20JYNNEOS%E2%84%A2%20effectiveness%20as%20post-exposure%20prophylaxi.pdf)

7. NCD Risk Factor Collaboration (NCD-RisC). (2021) "Worldwide trends in hypertension prevalence and progress in treatment and control from 1990 to 2019: a pooled analysis of 1201 population-representative studies with 104 million participants". *The Lancet*. 398(10304), 957–980. [https://doi.org/10.1016/S0140-6736(21)01330-1](https://doi.org/10.1016/S0140-6736(21)01330-1) </br> {{< iconify fa-regular file-pdf >}} [pdf](files/Zhou%20et%20al.%20-%202021%20-%20Worldwide%20trends%20in%20hypertension%20prevalence%20and%20pr.pdf)


### Dissertation
- **Boyer, C.** (2023) "New approaches to factual and counterfactual prediction modeling". *Doctoral dissertation*, Harvard University Graduate School of Arts and Sciences. </br> {{< iconify fa-regular file-pdf >}} [pdf](https://dash.harvard.edu/bitstream/handle/1/37374603/thesis.pdf) / {{< iconify file-icons keynote >}} [slides](files/defense.pdf)

