---
title: "Research"
description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Selected Publications
- **Boyer, C.**, Paluck, E. L., Annan, J., Nevatia, T., Cooper, J., Namubiru, J, Heise, L., & Lehrer, R. (2022) "Religious leaders can motivate men to cede power and reduce intimate partner violence: experimental evidence from Uganda". *PNAS*. 119(31), e2200262119. https://doi.org/10.1073/pnas.2200262119 

<aside>
📝 [pre-analysis plan](https://www.socialscienceregistry.org/trials/3994/history/43131) 

💾 [data & code](https://doi.org/10.7910/DVN/9TEAIV)
</aside>

- **Boyer, C.**, Rumpler, E., Kissler, S. M., & Lipsitch, M. (2022). "Infectious disease dynamics and restrictions on social gathering size". *Epidemics*, 40, 100620. https://doi.org/10.1016/j.epidem.2022.100620

<aside>
🖨 [pre-print](https://www.medrxiv.org/content/10.1101/2022.01.07.21268585v2)

💾 [data & code](https://github.com/boyercb/covid-gathering-size)
</aside>

- Chatterji, S., **Boyer, C.**, Sharma, V., Abramsky, T., Levtov, R., Doyle, K., Harvey, S., & Heise, L. (2023). "Optimizing the Construction of Outcome Measures for Impact Evaluations of Intimate Partner Violence Prevention Interventions." *Journal of Interpersonal Violence*, 0(0). https://doi.org/10.1177/08862605231162887

<aside>
🖨 [pre-print](https://www.medrxiv.org/content/10.1101/2023.02.07.23285510.abstract)

</aside>

- NCD Risk Factor Collaboration (NCD-RisC). (2021) "Worldwide trends in hypertension prevalence and progress in treatment and control from 1990 to 2019: a pooled analysis of 1201 population-representative studies with 104 million participants". *The Lancet*. 398(10304), 957–980. https://doi.org/10.1016/S0140-6736(21)01330-1


### Pre-prints
- **Boyer, C.**, Dahabreh, I. J., & Steingrimsson, J. A. (2023). "Assessing model performance for counterfactual predictions". *arXiv.* https://doi.org/10.48550/arXiv.2308.13026

- **Boyer, C.** & Lipsitch, M. (2023). "Defining and emulating target trials of the effects of postexposure vaccination using observational data". *medRxiv.* https://doi.org/10.1101/2023.05.03.23289471

- Joshi, K., Kahn, R., **Boyer, C.**, & Lipsitch, M. (2023). "Some principles for using epidemiologic study results to parameterize transmission models". *medRxiv.*  https://doi.org/10.1101/2023.10.03.23296455

- **Boyer, C.**, Chatterji, S., Cooper, J., & Heise, L. (2022). "Outcome coding choice in randomized trials of programs to reduce violence". *ArXiv:2204.12385 [Stat]*. http://arxiv.org/abs/2204.12385


### Dissertation
- **Boyer, C.** (2023) "New approaches to factual and counterfactual prediction modeling". *Doctoral dissertation*, Harvard University Graduate School of Arts and Sciences. 

<aside>
🖨 [archive](https://dash.harvard.edu/bitstream/handle/1/37374603/thesis.pdf)

🗒 [slides](files/defense.pdf)
</aside>

### Work in Progress
- **Boyer, C.** & Field, E. (2023) "*Hablemos entre patas*: a randomized-controlled trial of facilitated men's groups using WhatsApp to reduce intimate partner violence". *Manuscript in preparation*.

<aside>
📝 [pre-analysis plan](https://www.socialscienceregistry.org/trials/10043)
</aside>

- **Boyer, C.**, Paluck, E. L., Annan, J., Nevatia, T., Cooper, J., Namubiru, J, Heise, L., & Lehrer, R. (2023) "Does asking about violence increase reporting at subsequent interviews? Evidence from a randomized trial in Uganda". *Under review*

- NCD Risk Factor Collaboration (NCD-RisC). (2023) ``Long-term and recent trends in serum cholesterol treatment and control in 14 high-income countries: an analysis of 125 nationally representative surveys''.

- **Boyer, C.**, Beam, A., Robins, J, & Danaei, G. (2023) "Factual and counterfactual risk prediction using the parametric g-formula". *Dissertation paper*.
- **Boyer, C.**, Beam, A., Robins, J, & Danaei, G. (2023) "Target trials for prediction: emulating a trial to estimate the treatment-naive risk". *Dissertation paper*.








