---
title: "The reasons people start treatment are not the same as the reasons they stop"
subtitle: | 
    And what this implies for causal inference for sustained treatment strategies.
date: "2024-02-16"
categories: [causal inference, code, g-formula]
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(dagtex)

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center"
  # out.width = "100%"
)
new_opts <- list(
  dagtex.adorn_math = TRUE,
  dagtex.swig_options = list(
    shape = "ellipse",
    text_right = "red",
    line_color_right = "red",
    line_color_lower = "red",
    text_lower = "red"
  ),
  dagtex.node_options = list(shape = "ellipse", draw = "none")
)
options(new_opts)
```

Researchers are often interested in estimating the effects of sustained use of a treatment on a health outcome.

\begin{align}
L_0 \sim
A_0 \sim
L_1 \sim
A_1 \sim
Y
\end{align}

```{r dag-1, out.width = "100%", dpi=600, fig.retina=2}
#| fig-cap: "A directed acyclic graph for a single, time-fixed treatment. "

dag1 <-
  dagtex(
    node_options = list(shape = "ellipse", draw = "none"),
    edge_options = list(color = "black"),
    swig_options = list(gap = "3pt", line_color_right = "red", shape = "ellipse"),
    adorn_math = TRUE
  ) %>%
  add_node(list("L_0", c("A_0", "a_0"),"L_1", "A_1", "Y")) %>%
  adorn_counterfactuals()

dag1
```